project:
  type: website

execute:
  freeze: auto 

jupyter:
  kernelspec:
    name: porta
    language: python
    display_name: porta
    
website:
  title: "Gabriel Velazquez | Physics "
  navbar:
    left:
      - href: index.qmd
        text: Principal Page
      - href: about.qmd
        text: About me
      - href: proyectos.qmd
        text: Projects

format:
  html:
    theme: darkly
    css: styles.css
    toc: true